config:
  fullscreen: false
  godmode: false
levels:
  - enemies:
      Basic: 40
    background: background.png
  - enemies:
      Basic: 40
      Advanced: 30
    background: background2.png
  - enemies:
      Advanced: 30
      BasicAngry: 35
      Basic: 20
    background: background3.png
enemies:
  Basic:
    speed: 3
    image: enemy.png
    size: 32
    hostility: 4
  BasicAngry:
    speed: 4
    image: enemy3.png
    size: 32
    hostility: 8
  Advanced:
    speed: 4
    image: enemy2.png
    size: 28
    hostility: 6
