config:
  fullscreen: false
  godmode: false
levels:
  - enemies:
      Basic: 2
      Advanced: 5
    background: background.png
  - enemies:
      Basic: 40
    background: background2.png
enemies:
  Basic:
    speed: 3
    image: enemy.png
    size: 32
  Advanced:
    speed: 5
    image: enemy2.png
    size: 64
