config:
  fullscreen: false
  godmode: false
levels:
  - enemies:
      Basic: 10
    background: background.png
  - enemies:
      Basic: 30
    background: background2.jpg
enemies:
  Basic:
    speed: 3
    image: enemy.gif
    size: 32
