config:
  fullscreen: false
  godmode: false
levels:
  - enemies:
      Basic: 25
    background: background.png
  - enemies:
      Basic: 40
      Advanced: 20
    background: background2.png
enemies:
  Basic:
    speed: 3
    image: enemy.png
    size: 32
  Advanced:
    speed: 4
    image: enemy2.png
    size: 28
